version: '3.7'

services:
  development:
    container_name: development
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8080:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: node index.js